spring.application.name=edu-track
# Database URL (edutrack_db k?sm?n? Postgres'te olu?turdu?un db ismiyle de?i?tir)
spring.datasource.url=jdbc:postgresql://localhost:5432/edutrack_db
spring.datasource.username=postgres
spring.datasource.password=nestedfolders

# Hibernate Ayarlar?
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
# create-drop:
# Uygulama baslarken tüm tablolari siler
# ve sifirdan olusturur. Uygulama kapandiginda ise
# tablolari siler.
# create:
# Baslarken siler ve olusturur, kapaninca silmez.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect